/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AssignedResource {
  resourceId: string
  quantityUsed: number
}

export declare const enum DependencyType {
  FinishToStart = 'FinishToStart',
  StartToStart = 'StartToStart',
  FinishToFinish = 'FinishToFinish',
  StartToFinish = 'StartToFinish'
}

export interface Resource {
  id: string
  name: string
  kind: ResourceKind
  capacity: number
  roles: Array<string>
}

export interface ResourceInventory {
  items: Array<ResourceInventoryItem>
}

export interface ResourceInventoryItem {
  resourceId: string
  availableQuantity: number
}

export declare const enum ResourceKind {
  Equipment = 'Equipment',
  People = 'People',
  Consumable = 'Consumable'
}

export interface ResourceNeed {
  resourceId: string
  quantity: number
  minPeople?: number
  maxPeople?: number
}

export interface ScheduleSummary {
  totalDurationMins: number
  criticalPathStepIds: Array<string>
}

export interface ScheduleTemplate {
  id: string
  name: string
  description?: string
  steps: Array<Step>
  tracks: Array<Track>
  resources: Array<Resource>
  timeConstraint?: TimeConstraint
  defaultNumPeople?: number
}

/** Stub for the schedule solver. Phase 2 will implement the actual engine. */
export declare function solve(template: ScheduleTemplate, inventory?: ResourceInventory | undefined | null): SolvedSchedule

export interface SolvedSchedule {
  templateId: string
  solvedSteps: Array<SolvedStep>
  summary: ScheduleSummary
  warnings: Array<string>
}

export interface SolvedStep {
  stepId: string
  startOffsetMins: number
  endOffsetMins: number
  startTime?: string
  endTime?: string
  assignedResources: Array<AssignedResource>
}

export interface Step {
  id: string
  title: string
  description?: string
  durationMins: number
  dependencies: Array<StepDependency>
  trackId?: string
  timingPolicy?: TimingPolicy
  resourceNeeds: Array<ResourceNeed>
}

export interface StepDependency {
  stepId: string
  dependencyType: DependencyType
}

export interface TimeConstraint {
  startTime?: string
  endTime?: string
}

export declare const enum TimingPolicy {
  Asap = 'Asap',
  Alap = 'Alap'
}

export interface Track {
  id: string
  name: string
}
