/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Smoke test: proves napi-rs FFI works end-to-end.
 * Will be replaced by real exports in Plan 01-02.
 */
export declare function ping(): string
